export const ngoCollections = {
  children: {
    title: "Children Records",
    description:
      "Track beneficiary profiles, schooling status, health flags, and center allocations.",
    storageKey: "ngo_children_records",
    seed: [
      {
        id: "child-001",
        childName: "Aarav Kumar",
        age: "9",
        gender: "Boy",
        center: "Tigra Learning Hub",
        guardian: "Sunita Devi",
        educationLevel: "Class 3",
        healthStatus: "Stable",
        status: "Active",
        notes: "Needs reading support and monthly nutrition review.",
      },
      {
        id: "child-002",
        childName: "Meera Singh",
        age: "11",
        gender: "Girl",
        center: "Sector 57 Center",
        guardian: "Rakesh Singh",
        educationLevel: "Class 5",
        healthStatus: "Under Observation",
        status: "Active",
        notes: "Priority for dental camp and school bag support.",
      },
    ],
    fields: [
      { name: "childName", label: "Child Name", type: "text", required: true },
      { name: "age", label: "Age", type: "number", required: true },
      {
        name: "gender",
        label: "Gender",
        type: "select",
        options: ["Boy", "Girl", "Other"],
        required: true,
      },
      { name: "center", label: "Center", type: "text", required: true },
      { name: "guardian", label: "Guardian", type: "text", required: true },
      {
        name: "educationLevel",
        label: "Education Level",
        type: "text",
        required: true,
      },
      {
        name: "healthStatus",
        label: "Health Status",
        type: "select",
        options: ["Stable", "Under Observation", "Needs Medical Review"],
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "Paused", "Completed"],
        required: true,
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      "childName",
      "age",
      "center",
      "guardian",
      "healthStatus",
      "status",
    ],
  },
  employees: {
    title: "Employee Records",
    description:
      "Maintain staff profiles, roles, contact data, and active employment status.",
    storageKey: "ngo_employee_records",
    seed: [
      {
        id: "emp-001",
        employeeName: "Neha Sharma",
        role: "Program Manager",
        phone: "9876543210",
        center: "Head Office",
        dutyShift: "Morning",
        joinDate: "2024-02-14",
        status: "Active",
        notes: "Oversees school tie-ups and reporting.",
      },
      {
        id: "emp-002",
        employeeName: "Imran Khan",
        role: "Field Coordinator",
        phone: "9988776655",
        center: "Tigra Learning Hub",
        dutyShift: "Afternoon",
        joinDate: "2023-11-03",
        status: "Active",
        notes: "Manages center attendance and community visits.",
      },
    ],
    fields: [
      {
        name: "employeeName",
        label: "Employee Name",
        type: "text",
        required: true,
      },
      { name: "role", label: "Role", type: "text", required: true },
      { name: "phone", label: "Phone", type: "text", required: true },
      {
        name: "center",
        label: "Assigned Center",
        type: "text",
        required: true,
      },
      {
        name: "dutyShift",
        label: "Duty Shift",
        type: "select",
        options: ["Morning", "Afternoon", "Evening", "Night"],
        required: true,
      },
      { name: "joinDate", label: "Join Date", type: "date", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "On Leave", "Inactive"],
        required: true,
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      "employeeName",
      "role",
      "center",
      "dutyShift",
      "joinDate",
      "status",
    ],
  },
  duties: {
    title: "Duty Roster",
    description:
      "Assign weekly shifts, accountability, and field duties for each team member.",
    storageKey: "ngo_duty_roster",
    seed: [
      {
        id: "duty-001",
        dutyName: "Morning Attendance Check",
        assignedTo: "Neha Sharma",
        center: "Sector 57 Center",
        day: "Monday",
        shift: "Morning",
        priority: "High",
        status: "Scheduled",
        notes: "Verify nutrition register before class starts.",
      },
      {
        id: "duty-002",
        dutyName: "Health Camp Coordination",
        assignedTo: "Imran Khan",
        center: "Tigra Learning Hub",
        day: "Thursday",
        shift: "Afternoon",
        priority: "Medium",
        status: "Scheduled",
        notes: "Coordinate with pediatric doctor and parents.",
      },
    ],
    fields: [
      { name: "dutyName", label: "Duty Name", type: "text", required: true },
      {
        name: "assignedTo",
        label: "Assigned To",
        type: "text",
        required: true,
      },
      { name: "center", label: "Center", type: "text", required: true },
      {
        name: "day",
        label: "Day",
        type: "select",
        options: [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
          "Sunday",
        ],
        required: true,
      },
      {
        name: "shift",
        label: "Shift",
        type: "select",
        options: ["Morning", "Afternoon", "Evening", "Night"],
        required: true,
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        options: ["High", "Medium", "Low"],
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Scheduled", "In Progress", "Completed"],
        required: true,
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: ["dutyName", "assignedTo", "day", "shift", "priority", "status"],
  },
  programs: {
    title: "Program Control",
    description:
      "Manage current initiatives, budgets, progress, and ownership across centers.",
    storageKey: "ngo_program_records",
    seed: [
      {
        id: "prog-001",
        programName: "Project JEEVAN",
        owner: "Neha Sharma",
        beneficiaries: "120",
        budget: "250000",
        progress: "72",
        status: "Active",
        notes: "Includes school kits, digital literacy, and bridge coaching.",
      },
      {
        id: "prog-002",
        programName: "Nutrition Security Drive",
        owner: "Imran Khan",
        beneficiaries: "180",
        budget: "175000",
        progress: "58",
        status: "Active",
        notes: "Tracks meal distribution and weekly growth monitoring.",
      },
    ],
    fields: [
      {
        name: "programName",
        label: "Program Name",
        type: "text",
        required: true,
      },
      { name: "owner", label: "Program Owner", type: "text", required: true },
      {
        name: "beneficiaries",
        label: "Beneficiaries",
        type: "number",
        required: true,
      },
      { name: "budget", label: "Budget (INR)", type: "number", required: true },
      { name: "progress", label: "Progress %", type: "number", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Active", "Paused", "Archived"],
        required: true,
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    columns: [
      "programName",
      "owner",
      "beneficiaries",
      "progress",
      "budget",
      "status",
    ],
  },
};
